### PR TITLE
[SQL] Improve the implementation of several array functions

### LINKED ISSUE #3256: [SQL] "compilation error: array elements and arguments of different types" but compiles fine when simplified
SQL:

```sql
CREATE TABLE t0(c0 int) with ('materialized' = 'true');

CREATE MATERIALIZED VIEW v6_optimized AS (
    SELECT 1 FROM t0 WHERE 
    FALSE -- make this true and it compiles fine
    NOT BETWEEN 
    (
        (
            '7983-8-6 4:8:10'::TIMESTAMP IS DISTINCT FROM '6895-2-30 16:1:47'::TIMESTAMP -- simplify this and it compiles fine
        ) NOT BETWEEN (
            ARRAY_CONTAINS(array[1.531442425, 1.542531961E9, 5.09355347E8], 1.0164673495) -- this expression compiles fine on its own
        ) AND true
    ) 
    AND true
);
```

This fails to compile with:

```sql
array elements and argument of different types:
Fist argument is an array of type: d and second argument is of type: DECIMAL(11, 10)
```

However, the ARRAY expression compiles fine on its own:

```sql
create view v0 as select ARRAY_CONTAINS(array[1.531442425, 1.542531961E9, 5.09355347E8], 1.0164673495);
```

### LINKED ISSUE #3257: [SQL] RustError: array_to_string expects String found Time
SQL:

```sql
CREATE MATERIALIZED VIEW v7_optimized AS (SELECT ARRAY_TO_STRING(array[CAST('1:17:23' AS TIME), CAST('3:9:29' AS TIME)], ''));
```

SQL compilation passes but Rust compilation fails with:

Error:

```rust
Rust error: the Rust code generated based on the SQL (possibly combined with any user-provided UDF Rust and TOML code) failed to compile.
This should not happen (except if the error is in user-provided UDF code).
Please file a bug report with the example SQL and any UDF Rust/TOML that triggers it at:
https://github.com/feldera/feldera/issues


The compilation task exited with status code 101 and produced the following logs:

stderr:
   Compiling project-1c47a5a441cb9049b5c35a79689c40eda435b390572e7520b2e024d2d616d4fb v0.1.0 (/home/abhizer/.feldera/compiler/rust-compilation/projects/project-1c47a5a441cb9049b5c35a79689c40eda435b390572e7520b2e024d2d616d4fb)
error[E0308]: mismatched types
   --> projects/project-1c47a5a441cb9049b5c35a79689c40eda435b390572e7520b2e024d2d616d4fb/src/main.rs:104:21
    |
104 |                     Time::new(4643000000000/*01:17:23*/), Time::new(11369000000000/*03:09:29*/), ),
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `String`, found `Time`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `project-1c47a5a441cb9049b5c35a79689c40eda435b390572e7520b2e024d2d616d4fb` (bin "project-1c47a5a441cb9049b5c35a79689c40eda435b390572e7520b2e024d2d616d4fb") due to 1 previous error


stdout:
```

### LINKED ISSUE #3258: [SQL] RustError: function `arrays_overlap_vec_vec__vec_vec_` not found
SQL:

```sql
CREATE TABLE t0(c0 int) with ('materialized' = 'true');

CREATE MATERIALIZED VIEW v6_optimized AS (SELECT COUNT(1) FROM t0 WHERE ARRAYS_OVERLAP(array[array[CAST('1173-8-15 5:11:20' AS TIMESTAMP)]], array[array[CAST('5973-8-27 8:0:9' AS TIMESTAMP)]]));
```

The SQL compilation succeeds but the Rust compilation fails with:

```rust
Rust error: the Rust code generated based on the SQL (possibly combined with any user-provided UDF Rust and TOML code) failed to compile.
This should not happen (except if the error is in user-provided UDF code).
Please file a bug report with the example SQL and any UDF Rust/TOML that triggers it at:
https://github.com/feldera/feldera/issues


The compilation task exited with status code 101 and produced the following logs:

stderr:
   Compiling project-1ed528120b26abc1bcd3d21d3168f22df1c848ebd49594eadb3aeff00410cbf3 v0.1.0 (/home/abhizer/.feldera/compiler/rust-compilation/projects/project-1ed528120b26abc1bcd3d21d3168f22df1c848ebd49594eadb3aeff00410cbf3)
error[E0425]: cannot find function `arrays_overlap_vec_vec__vec_vec_` in this scope
   --> projects/project-1ed528120b26abc1bcd3d21d3168f22df1c848ebd49594eadb3aeff00410cbf3/src/main.rs:127:13
    |
127 |               arrays_overlap_vec_vec__vec_vec_(
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `arrays_overlap_vec__vec_`
    |
   ::: /mnt/hdd0/Development/feldera.git/main/crates/sqllib/src/array.rs:499:1
    |
499 | / pub fn arrays_overlap_vec__vec_<T>(first: Vec<T>, second: Vec<T>) -> bool
500 | | where
501 | |     T: Eq + Hash,
    | |_________________- similarly named function `arrays_overlap_vec__vec_` defined here

For more information about this error, try `rustc --explain E0425`.
error: could not compile `project-1ed528120b26abc1bcd3d21d3168f22df1c848ebd49594eadb3aeff00410cbf3` (bin "project-1ed528120b26abc1bcd3d21d3168f22df1c848ebd49594eadb3aeff00410cbf3") due to 1 previous error


stdout:
```

### PR DESCRIPTION
**Pull request by mihaibudiu**
I have changed the semantics of functions ARRAYS_OVERLAP, ARRAY_POSITION, ARRAY_INSERT, ARRAY_REMOVE.
ARRAYS_OVERLAP had a completely insane semantics with regards to null values in arrays. Now it behaves as any normal person would expect.

The other functions were behaving very strangely when types did not match. 
I am taking advantage of the new infra which allows us to not follow existing Calcite semantics for existing functions.

Fixes #3258
Fixes #3257 
Fixes #3256

### CODE REVIEW

**Review by abhizer — APPROVED** [review]
Ah nice! This is a lot neater than the Calcite semantics.
