### ISSUE TITLE
[SQL] "compilation error: array elements and arguments of different types" but compiles fine when simplified

### ISSUE THREAD

**Issue by abhizer** [feldera/feldera#3256]
SQL:

```sql
CREATE TABLE t0(c0 int) with ('materialized' = 'true');

CREATE MATERIALIZED VIEW v6_optimized AS (
    SELECT 1 FROM t0 WHERE 
    FALSE -- make this true and it compiles fine
    NOT BETWEEN 
    (
        (
            '7983-8-6 4:8:10'::TIMESTAMP IS DISTINCT FROM '6895-2-30 16:1:47'::TIMESTAMP -- simplify this and it compiles fine
        ) NOT BETWEEN (
            ARRAY_CONTAINS(array[1.531442425, 1.542531961E9, 5.09355347E8], 1.0164673495) -- this expression compiles fine on its own
        ) AND true
    ) 
    AND true
);
```

This fails to compile with:

```sql
array elements and argument of different types:
Fist argument is an array of type: d and second argument is of type: DECIMAL(11, 10)
```

However, the ARRAY expression compiles fine on its own:

```sql
create view v0 as select ARRAY_CONTAINS(array[1.531442425, 1.542531961E9, 5.09355347E8], 1.0164673495);
```
