### ISSUE TITLE
MAP with VARIANT value type causes runtime panic in dbsp

### ISSUE THREAD

**Issue by bts** [feldera/feldera#3277]
**Describe the bug**

While trying to work around #3262 I changed one of my column types (well it's actually nested in a `ROW`...) from `Attributes MAP<VARCHAR, ROW(Value VARCHAR)>` to `Attributes VARIANT`. That caused some serde errors in the logs which may or may not be expected:

```
[pipeline-0193b683-0ff8-7da0-9342-e8eacf097584] 2025-01-09T03:19:00.682102Z ERROR dbsp_adapters::server: parse error on input endpoint 'nodes.d183e4c55a': Parse error: error deserializing table records from Parquet data: Error: serde::de::Error: {"field":"node_body","description":"Error: serde::de::Error: {\"field\":\"attributes\",\"description\":\"Error: Deserializer does not implement deserialize_string (data_type: \\\"Map(..)\\\", field: \\\"$.node_body.Attributes\\\")\"} (data_type: \"Struct(..)\", field: \"$.node_body\")"} (data_type: "Struct(..)", field: "$")
Invalid bytes: []
```

but when I changed this type to `Attributes MAP<VARCHAR, VARIANT>` it caused a runtime panic in dbsp. See the collapsed stack trace below.

<details><summary>Stack trace</summary>
<p>

```
[pipeline-0193b683-0ff8-7da0-9342-e8eacf097584] 2025-01-09T03:28:50.172045Z ERROR dbsp_adapters::server: Response: 503 Service Unavailable (size: Sized(125)) to request GET /stats
   0: rust_begin_unwind
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
   2: core::panicking::panic
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:148:5
   3: core::option::unwrap_failed
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/option.rs:2012:5
   4: unwrap<&alloc::boxed::Box>
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/option.rs:972:21
   5: columntype_to_datatype
             at ./database-stream-processor/crates/adapters/src/format/parquet/mod.rs:286:47
   6: field_to_arrow_field
             at ./database-stream-processor/crates/adapters/src/format/parquet/mod.rs:221:13
   7: {closure#0}
             at ./database-stream-processor/crates/adapters/src/format/parquet/mod.rs:231:26
   8: {closure#0}<&feldera_types::program_schema::Field, arrow_schema::field::Field, (), dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}, core::iter::traits::iterator::Iterator::for_each::call::{closure_env#0}, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}>>>>
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/iter/adapters/map.rs:88:28
   9: fold, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}>>>>>
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/slice/iter/macros.rs:232:27
  10: fold, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}, (), core::iter::traits::iterator::Iterator::for_each::call::{closure_env#0}, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}>>>>
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/iter/adapters/map.rs:128:9
  11: for_each, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}>, alloc::vec::{impl#20}::extend_trusted::{closure_env#0}, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}>>>
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/iter/traits/iterator.rs:813:9
  12: extend_trusted, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}>>
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/alloc/src/vec/mod.rs:3524:17
  13: spec_extend, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}>, alloc::alloc::Global>
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/alloc/src/vec/spec_extend.rs:26:9
  14: from_iter, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}>>
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/alloc/src/vec/spec_from_iter_nested.rs:60:9
  15: from_iter, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}>>
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/alloc/src/vec/spec_from_iter.rs:33:9
  16: from_iter, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}>>
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/alloc/src/vec/mod.rs:3388:9
  17: collect, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}>, alloc::vec::Vec>
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/iter/traits/iterator.rs:2001:9
  18: struct_to_arrow_fields
             at ./database-stream-processor/crates/adapters/src/format/parquet/mod.rs:232:18
  19: columntype_to_datatype
             at ./database-stream-processor/crates/adapters/src/format/parquet/mod.rs:281:49
  20: field_to_arrow_field
             at ./database-stream-processor/crates/adapters/src/format/parquet/mod.rs:221:13
  21: {closure#0}
             at ./database-stream-processor/crates/adapters/src/format/parquet/mod.rs:231:26
  22: {closure#0}<&feldera_types::program_schema::Field, arrow_schema::field::Field, (), dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}, core::iter::traits::iterator::Iterator::for_each::call::{closure_env#0}, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}>>>>
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/iter/adapters/map.rs:88:28
  23: fold, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}>>>>>
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/slice/iter/macros.rs:232:27
  24: fold, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}, (), core::iter::traits::iterator::Iterator::for_each::call::{closure_env#0}, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}>>>>
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/iter/adapters/map.rs:128:9
  25: for_each, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}>, alloc::vec::{impl#20}::extend_trusted::{closure_env#0}, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}>>>
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/iter/traits/iterator.rs:813:9
  26: extend_trusted, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}>>
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/alloc/src/vec/mod.rs:3524:17
  27: spec_extend, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}>, alloc::alloc::Global>
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/alloc/src/vec/spec_extend.rs:26:9
  28: from_iter, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}>>
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/alloc/src/vec/spec_from_iter_nested.rs:60:9
  29: from_iter, dbsp_adapters::format::parquet::relation_to_arrow_fields::struct_to_arrow_fields::{closure_env#0}>>
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/alloc/src/vec/spec_from_iter.rs:33:9
  30: from_iter, dbsp_adapters::format::parquet::relation_to_arrow_fields::{closure_env#0}>>
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/alloc/src/vec/mod.rs:3388:9
  31: collect, dbsp_adapters::format::parquet::relation_to_arrow_fields::{closure_env#0}>, alloc::vec::Vec>
             at ./rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/iter/traits/iterator.rs:2001:9
  32: relation_to_arrow_fields
             at ./database-stream-processor/crates/adapters/src/format/parquet/mod.rs:316:10
  33: initialize_adhoc_queries
             at ./database-stream-processor/crates/adapters/src/controller/mod.rs:1771:32
  34: new
             at ./database-stream-processor/crates/adapters/src/controller/mod.rs:1736:9
  35: new
             at ./database-stream-processor/crates/adapters/src/controller/mod.rs:500:75
  36: {closure#0}
             at ./database-stream-processor/crates/adapters/src/controller/mod.rs:189:35
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details> 

**To Reproduce**

Unfortunately this is not going to be very easy to reproduce because it's a function of data I'm passing in at runtime that I can't easily sanitize at the moment, but if it's not clear from the errors above what might be going on, I would be happy to try to spend some time constructing a minimal reproducing case.

**Expected behavior**

Successful deserialization if possible, logged serde errors if not, or perhaps a compile time error if a given configuration of types is known not to be supported.

**Screenshots**

**Context (please complete the following information):**
 - Environment: Cloud Sandbox on Jan 8, 2025
 - Pipeline Configuration/SQL code:

```
CREATE TABLE fails (  
        a VARCHAR,
        b VARCHAR,
        c VARCHAR,
        d VARCHAR,
        e VARCHAR,
        f VARCHAR,
        g VARCHAR,
        h VARCHAR,
        i MAP<VARCHAR, VARCHAR>,
        j ROW(
            k ROW(
                l VARCHAR
            ),
            m ROW(
                n ROW(
                    o ROW(
                        p VARCHAR,
                        q VARCHAR
                    ),
                    r VARCHAR
                )
            ),
        
            -- fails at compile time due to #3262
            --s MAP<VARCHAR, ROW(
            --    t VARCHAR
            --)>

            -- causes "Deserializer does not implement deserialize_string" errors at runtime
            --s VARIANT

            -- compiles but panics:
            s MAP<VARCHAR, VARIANT>
        ),
        u VARCHAR,
        v BIGINT,
        w BIGINT,
        x BIGINT
    )
```

**Additional context**

This is related to the compile-time bug #3262.

**Comment by bts** [comment]
cc @mihaibudiu -- related to #3262

**Comment by ryzhyk** [comment]
@bts , I believe @mihaibudiu has already fixed this panic in his draft PR. @mihaibudiu , any chance you could make a separate PR with just this fix.

**Comment by ryzhyk** [comment]
As for the parser error, it's probably a valid error in that it is not possible to deserialize parquet MAP directly into VARIANT.

**Comment by ryzhyk** [comment]
@bts , the panic should now be fixed.

**Comment by bts** [comment]
thanks @ryzhyk!

**Comment by mihaibudiu** [comment]
Hope to close today a few of the other bugs you reported as well.
